Previews for pictures that displayed on the screen instead of all.
area9innovation/flow9 pull request #921
Opened 2021-11-26 13:59 UTC by SLemishko

Additionally add preview of the pictures in search mode.

https://trello.com/c/cMevJitP/16244-speed-up-filebrowser-for-large-partitions?filter=label:Release%202.5

2021-11-26 14:01 UTC, SLemishko commented
![Before-After-Search](https://user-images.githubusercontent.com/88338441/143592233-820067a7-13ee-475f-8396-8c7d761c6dd6.jpg)

2021-11-26 17:14 UTC, NikitaFil requested changes
Generally looks fine, but one more fix is needed.

2021-11-26 17:14 UTC, NikitaFil commented on lib/material/internal/filebrowser/material_filebrowser_internal_view.flow
> +					createItemUI(state, newCPItem, changeItem, requestPreview)
state.contentViewIconsB is now unsupported

2021-11-29 10:19 UTC, NikitaFil approved these changes

2021-11-29 12:00 UTC, MalkoVl reviewed
Some explanation are required.

2021-12-02 12:20 UTC, MalkoVl approved these changes

2021-12-02 13:07 UTC, merged