Added function to split int array to array of ranges.
area9innovation/flow9 pull request #932
Opened 2021-12-10 14:54 UTC by sergeymaksimov

2021-12-13 14:36 UTC, Eugeny48 requested changes
Try to use fold + List + list2array. The current implementation is very expensive

2021-12-13 14:36 UTC, Eugeny48 commented on lib/flowutils.flow
> +		if (length(ranges) < length(ids)) {
There is more cheap way to estimate: `if (foldi(ids, false, \i, acc, id -> acc || (i > 0 && ids[i - 1] + 1 == id)))`

2021-12-13 14:36 UTC, Eugeny48 commented on lib/flowutils.flow
> +			if (i > 0 && i < l && id - 1 == sorted[i - 1] && id + 1 == sorted[i + 1]) {
`i < l` is `true` always

2021-12-13 14:50 UTC, Eugeny48 commented on lib/flowutils.flow
> +		RequestIdsRanges(ranges : [[int]]);
Please, add a comment explaining what `RequestIdsRanges` contains.

2021-12-14 17:14 UTC, sergeymaksimov commented
> This way original string is even shorter. This rage should be "[[1, 2], 4, 6, 8]". No need for brackets around a single number, right?

Right.

2021-12-16 13:28 UTC, Eugeny48 approved these changes
Looks good.

2021-12-17 08:25 UTC, merged