Adding references to each block
area9innovation/flow9 pull request #965
Opened 2022-02-05 16:53 UTC by yanakrasnova

2022-02-18 15:06 UTC, andrejefimov approved these changes

2022-02-19 16:55 UTC, brawaga requested changes
These changes bring too much of HTML flavour.
Look at https://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown to find something more markdown-like, or look at innovation/lib/wigi/markdown for how we decided to define it.

2022-02-19 16:57 UTC, brawaga approved these changes
Oh, I am a slowpoke.

2022-02-21 13:33 UTC, merged

2022-02-21 13:35 UTC, andrejefimov commented
@yanakrasnova Please do not forget to delete merged branches